In [1]:
%run dt_author_id_Lucy

C:\Users\binglu\AppData\Local\Continuum\anaconda2\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


no. of Chris training emails: 7936
no. of Sara training emails: 7884
[0 0 1 ... 1 0 0]


ValueError: Expected 2D array, got 1D array instead:
array=[0. 1. 0. ... 0. 0. 1.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [2]:
%run dt_author_id_Lucy

no. of Chris training emails: 7936
no. of Sara training emails: 7884
[0 0 1 ... 1 0 1]
0.9931740614334471


In [3]:
%run dt_author_id_Lucy

no. of Chris training emails: 7936
no. of Sara training emails: 7884
[0 0 1 ... 1 0 0]
0.9960182025028441


ValueError: Number of features of the model must match the input. Model n_features is 3785 and input n_features is 2 

In [4]:
%run dt_author_id_Lucy

no. of Chris training emails: 7936
no. of Sara training emails: 7884
[0 0 1 ... 1 0 0]
0.9943117178612059


In [5]:
%run dt_author_id_Lucy

no. of Chris training emails: 7936
no. of Sara training emails: 7884
[0 0 1 ... 1 0 0]
0.9954493742889647


In [6]:
%run dt_author_id_Lucy

no. of Chris training emails: 7936
no. of Sara training emails: 7884
[0 0 1 ... 1 0 0]
0.9772468714448237


In [7]:
%run dt_author_id_Lucy

no. of Chris training emails: 7936
no. of Sara training emails: 7884
[0 0 1 ... 1 0 0]
0.9726962457337884
0.9726962457337884
1710


In [8]:
%run dt_author_id_Lucy

no. of Chris training emails: 7936
no. of Sara training emails: 7884
[0 0 1 ... 1 0 1]
0.9948805460750854
0.9948805460750854
1749


In [9]:
%run dt_author_id_Lucy

no. of Chris training emails: 7936
no. of Sara training emails: 7884
[0 0 1 ... 1 0 1]
0.9704209328782708
0.9704209328782708
1706
3785


In [10]:
%run dt_author_id_Lucy

no. of Chris training emails: 7936
no. of Sara training emails: 7884
[0 0 1 ... 1 0 0]
0.9783845278725825
0.9783845278725825
1720
3785


In [11]:
%run dt_author_id_Lucy

no. of Chris training emails: 7936
no. of Sara training emails: 7884
[0 0 1 ... 1 0 1]
0.9709897610921502
0.9709897610921502
1707
3785


In [12]:
%run dt_author_id_Lucy

no. of Chris training emails: 7936
no. of Sara training emails: 7884
[0 0 1 ... 1 0 1]
0.9749715585893061
0.9749715585893061
1714
3785


In [13]:
%run dt_author_id_Lucy

no. of Chris training emails: 7936
no. of Sara training emails: 7884
[0 0 1 ... 1 0 0]
0.9965870307167235
0.9965870307167235
1752
3785


In [14]:
%run dt_author_id_Lucy

no. of Chris training emails: 7936
no. of Sara training emails: 7884
[0 0 1 ... 1 0 0]
0.9937428896473265
0.9937428896473265
1747
3785


In [15]:
%run dt_author_id_Lucy

no. of Chris training emails: 7936
no. of Sara training emails: 7884
[0 0 1 ... 1 0 1]
0.9937428896473265
0.9937428896473265
1747
3785


In [16]:
%run dt_author_id_Lucy

no. of Chris training emails: 7936
no. of Sara training emails: 7884
[0 0 1 ... 1 0 1]
0.9948805460750854
0.9948805460750854
1749
3785


In [17]:
%run dt_author_id_Lucy

no. of Chris training emails: 7936
no. of Sara training emails: 7884


AttributeError: 'function' object has no attribute '__file__'

In [18]:
%run dt_author_id_Lucy

no. of Chris training emails: 7936
no. of Sara training emails: 7884


NameError: name 'email_preprocess' is not defined

In [19]:
%run dt_author_id_Lucy

no. of Chris training emails: 7936
no. of Sara training emails: 7884


TypeError: object of type 'function' has no len()

In [20]:
%run dt_author_id_Lucy

no. of Chris training emails: 7936
no. of Sara training emails: 7884
no. of Chris training emails: 7936
no. of Sara training emails: 7884


AttributeError: 'tuple' object has no attribute 'replace'

In [21]:
import email_preprocess


In [22]:
inspect. getfile(email_preprocess)

NameError: name 'inspect' is not defined

In [23]:
%run dt_author_id_Lucy

no. of Chris training emails: 7936
no. of Sara training emails: 7884


NameError: name 'inspect' is not defined

In [24]:
%run dt_author_id_Lucy

no. of Chris training emails: 7936
no. of Sara training emails: 7884
[0 0 1 ... 1 0 0]
0.9954493742889647
0.9954493742889647
1750
3785
