In [1]:
%run svm_author_id_Lucy

C:\Users\binglu\AppData\Local\Continuum\anaconda2\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


no. of Chris training emails: 7936
no. of Sara training emails: 7884
[0 0 1 ... 1 0 0]


ValueError: Expected 2D array, got 1D array instead:
array=[0. 0. 1. ... 1. 0. 0.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [2]:
%time
%run svm_author_id_Lucy

Wall time: 0 ns
no. of Chris training emails: 7936
no. of Sara training emails: 7884


AttributeError: 'builtin_function_or_method' object has no attribute 'time'

In [3]:
%run svm_author_id_Lucy

no. of Chris training emails: 7936
no. of Sara training emails: 7884


AttributeError: 'builtin_function_or_method' object has no attribute 'time'

In [4]:
%run svm_author_id_Lucy

no. of Chris training emails: 7936
no. of Sara training emails: 7884
1523315070.28
[0 0 1 ... 1 0 0]


ValueError: Expected 2D array, got 1D array instead:
array=[0. 0. 1. ... 1. 0. 0.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [5]:
%run svm_author_id_Lucy

no. of Chris training emails: 7936
no. of Sara training emails: 7884
1523316102.12
[0 0 1 ... 1 0 0]
215.30700016
0.9840728100113766


NameError: name 'y_pred' is not defined

In [6]:
%run svm_author_id_Lucy

no. of Chris training emails: 7936
no. of Sara training emails: 7884
1523316383.37
[0 0 1 ... 1 0 0]
213.434999943
0.9840728100113766
0.9840728100113766
1730


In [7]:
%run svm_author_id_Lucy

no. of Chris training emails: 7936
no. of Sara training emails: 7884
1523317106.35
[0 1 1 ... 1 0 1]
1.23099994659
0.8845278725824801
0.8845278725824801
1555


In [8]:
%run svm_author_id_Lucy

no. of Chris training emails: 7936
no. of Sara training emails: 7884
1523317339.41
[0 1 1 ... 1 1 1]
1.4880001545
0.6160409556313993
0.6160409556313993
1083


In [9]:
%run svm_author_id_Lucy

no. of Chris training emails: 7936
no. of Sara training emails: 7884
1523380605.57
[0 1 1 ... 1 1 1]
1.3900001049
0.6160409556313993
0.6160409556313993
1083


In [10]:
%time
%run svm_author_id_Lucy

Wall time: 0 ns
no. of Chris training emails: 7936
no. of Sara training emails: 7884
1523380666.62
[0 1 1 ... 1 1 1]
1.59500002861
0.6160409556313993
0.6160409556313993
1083


c=100

In [11]:
%time
%run svm_author_id_Lucy

Wall time: 0 ns
no. of Chris training emails: 7936
no. of Sara training emails: 7884
1523380926.59
[0 1 1 ... 1 1 1]
1.3789999485
0.6160409556313993
0.6160409556313993
1083


c=1000



In [12]:
%time
%run svm_author_id_Lucy

Wall time: 0 ns
no. of Chris training emails: 7936
no. of Sara training emails: 7884
1523380982.34
[0 1 1 ... 1 0 1]
1.38100004196
0.8213879408418657
0.8213879408418657
1444


c=1000

In [13]:
%time
%run svm_author_id_Lucy

Wall time: 0 ns
no. of Chris training emails: 7936
no. of Sara training emails: 7884
1523381045.0
[0 1 1 ... 1 0 1]
1.55900001526
0.8213879408418657
0.8213879408418657
1444


In [14]:
c=10000

In [15]:
%time
%run svm_author_id_Lucy

Wall time: 0 ns
no. of Chris training emails: 7936
no. of Sara training emails: 7884
1523381395.67
[0 1 1 ... 1 0 1]
1.14599990845
0.8924914675767918
0.8924914675767918
1569


In [16]:
c=100000


In [17]:
%time
%run svm_author_id_Lucy

Wall time: 0 ns
no. of Chris training emails: 7936
no. of Sara training emails: 7884
1523381442.32
[0 1 1 ... 1 0 1]
1.10700011253
0.8600682593856656
0.8600682593856656
1512


In [18]:
%time
%run svm_author_id_Lucy

Wall time: 0 ns
no. of Chris training emails: 7936
no. of Sara training emails: 7884
1523381908.0
[0 1 1 ... 1 0 1]
1.06700015068
0.8600682593856656


NameError: name 'predictions' is not defined

In [19]:
%time
%run svm_author_id_Lucy

Wall time: 0 ns
no. of Chris training emails: 7936
no. of Sara training emails: 7884
1523382179.3
[0 1 1 ... 1 0 1]
1.125
0.8600682593856656
1
0.8600682593856656
1512


In [20]:
%time
%run svm_author_id_Lucy

Wall time: 0 ns
no. of Chris training emails: 7936
no. of Sara training emails: 7884
1523382467.76
[0 1 1 ... 1 0 1]
1.125
0.8600682593856656
1 0 1
0.8600682593856656
1512


In [21]:
%time
%run svm_author_id_Lucy

Wall time: 0 ns


SyntaxError: invalid syntax (svm_author_id_Lucy.py, line 59)

In [22]:
%time
%run svm_author_id_Lucy

Wall time: 0 ns


SyntaxError: invalid syntax (svm_author_id_Lucy.py, line 59)

In [23]:
%time
%run svm_author_id_Lucy

Wall time: 0 ns


SyntaxError: invalid syntax (svm_author_id_Lucy.py, line 59)

In [24]:
%time
%run svm_author_id_Lucy

Wall time: 0 ns
no. of Chris training emails: 7936
no. of Sara training emails: 7884
1523382868.84
[0 1 1 ... 1 0 1]
1.12300014496
0.8924914675767918
1 0 1
0.8924914675767918
1569
0
1
2
2
3
3
4
4
4
5
6
6
7
7
8
8
9
9
10
10
11
12
13
13
13
14
14
15
16
17
18
18
18
19
20
20
20
20
20
20
21
21
21
22
23
24
25
25
26
26
27
28
28
29
29
30
31
31
32
33
33
34
35
36
37
37
38
38
38
39
40
40
41
42
42
43
43
44
45
46
46
47
47
48
49
50
51
51
52
52
53
53
54
55
56
57
57
58
58
58
58
59
60
61
61
61
62
62
63
64
65
66
67
68
68
69
70
71
72
72
73
74
75
75
75
76
76
77
78
79
80
81
81
82
83
84
84
84
85
86
87
88
88
88
89
89
89
90
90
90
90
91
91
91
92
93
93
93
94
95
95
95
95
96
96
97
98
99
100
101
101
102
102
102
103
104
105
106
106
106
106
106
107
108
109
109
110
111
112
113
114
115
116
117
118
119
120
120
120
121
121
121
122
123
123
123
123
124
125
126
127
127
128
128
128
129
129
129
129
130
131
131
132
132
132
133
133
134
135
136
137
138
138
138
138
138
138
139
140
141
142
142
143
143
143
144
144
144
144
145
146
14

In [25]:
%time
%run svm_author_id_Lucy

Wall time: 0 ns
no. of Chris training emails: 7936
no. of Sara training emails: 7884
1523383043.55
[0 1 1 ... 1 0 1]
1.25600004196
0.8924914675767918
1 0 1
0.8924914675767918
1569
1018


In [26]:
%time
%run svm_author_id_Lucy

Wall time: 0 ns
no. of Chris training emails: 7936
no. of Sara training emails: 7884
1523383074.18
[0 0 1 ... 1 0 0]
144.434999943
0.9908987485779295
1 0 1
0.9908987485779295
1742
877
